### ISSUE TITLE
Issue with the code

### ISSUE THREAD

**Issue by kjyothiswaroop** [cbsudux/Turtlesim-Move#2]
I downloaded the code and saved it into my workspace and ran it properly everything is working fine but the turtlesim window is not opening. In your code also I haven't found any module which is using the turtlesim package.

**Comment by cbsudux** [comment]
Hey buddy, I'm not actively maintaining this code and this is quite old. You can find a lot of similar codebases and tutorials on ROS itself : http://wiki.ros.org/turtlesim
